package generators

import (
	"fmt"
	"go/format"
	"strings"

	goten "github.com/dnahilman/goten"
)

type gormGenerator struct{}

// initialisms keeps generated Go field names idiomatic (UserID, not UserId).
var initialisms = map[string]string{
	"id": "ID", "ip": "IP", "url": "URL", "api": "API", "jwt": "JWT", "ttl": "TTL",
}

func (gormGenerator) Generate(schema map[string]goten.TableSchema, opts Options) (Result, error) {
	pkg := opts.Package
	if pkg == "" {
		pkg = "authmodels"
	}
	tables := orderedTables(schema, opts.TableOrder)

	var b strings.Builder
	b.WriteString("// Code generated by `goten generate`. DO NOT EDIT.\n")
	b.WriteString("package " + pkg + "\n\n")
	b.WriteString("__IMPORTS__\n\n")

	usesTime := false
	var allModels []string

	for _, table := range tables {
		ts := schema[table]
		model := structName(table)
		allModels = append(allModels, "&"+model+"{}")

		// Map each composite-unique member column to a shared index name.
		composite := map[string]string{}
		for _, group := range ts.UniqueTogether {
			idx := "uq_" + table + "_" + strings.Join(group, "_")
			for _, col := range group {
				composite[col] = idx
			}
		}

		b.WriteString("type " + model + " struct {\n")
		var assoc []goten.FieldDef
		for _, f := range ts.Fields {
			gt := goType(f)
			if strings.Contains(gt, "time.Time") {
				usesTime = true
			}
			b.WriteString(fmt.Sprintf("\t%s %s `gorm:%q`\n", toPascal(f.Name), gt, gormTag(f, composite)))
			if f.Ref != "" {
				assoc = append(assoc, f)
			}
		}
		for _, f := range assoc {
			refTable, refCol, ok := splitRef(f.Ref)
			if !ok {
				continue
			}
			b.WriteString(fmt.Sprintf(
				"\t%s *%s `gorm:\"foreignKey:%s;references:%s;constraint:OnDelete:CASCADE\"`\n",
				structName(refTable), structName(refTable), toPascal(f.Name), toPascal(refCol),
			))
		}
		b.WriteString("}\n\n")
		b.WriteString(fmt.Sprintf("func (%s) TableName() string { return %q }\n\n", model, table))
	}

	b.WriteString("// AllModels returns every generated model for db.AutoMigrate(...).\n")
	b.WriteString("func AllModels() []any {\n\treturn []any{" + strings.Join(allModels, ", ") + "}\n}\n")

	imports := ""
	if usesTime {
		imports = "import \"time\""
	}
	code := strings.Replace(b.String(), "__IMPORTS__", imports, 1)

	formatted, err := format.Source([]byte(code))
	if err != nil {
		return Result{}, fmt.Errorf("format generated code: %w", err)
	}
	return Result{Code: string(formatted)}, nil
}

func goType(f goten.FieldDef) string {
	var base string
	switch f.Type {
	case "boolean":
		base = "bool"
	case "integer":
		base = "int64"
	case "timestamp":
		base = "time.Time"
	default:
		base = "string"
	}
	if !f.Required && !f.PrimaryKey {
		return "*" + base
	}
	return base
}

func gormTag(f goten.FieldDef, composite map[string]string) string {
	parts := []string{"column:" + f.Name}
	if f.PrimaryKey {
		parts = append(parts, "primaryKey")
	}
	if f.Unique {
		parts = append(parts, "uniqueIndex")
	}
	if f.Index {
		parts = append(parts, "index")
	}
	if name, ok := composite[f.Name]; ok {
		parts = append(parts, "uniqueIndex:"+name)
	}
	if f.Required && !f.PrimaryKey {
		parts = append(parts, "not null")
	}
	if f.Default != "" {
		parts = append(parts, "default:"+f.Default)
	}
	return strings.Join(parts, ";")
}

// toPascal converts a snake_case column name to a PascalCase Go field name,
// upper-casing known initialisms (user_id → UserID, id_token → IDToken).
func toPascal(s string) string {
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if p == "" {
			continue
		}
		if up, ok := initialisms[strings.ToLower(p)]; ok {
			parts[i] = up
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, "")
}

// structName derives a Go struct name from a table name (users → User,
// accounts → Account, verification → Verification).
func structName(table string) string {
	singular := table
	// Only strip a trailing "s" (not "ss"), which covers users/sessions/accounts
	// while leaving already-singular names like "verification" untouched.
	if strings.HasSuffix(singular, "s") && !strings.HasSuffix(singular, "ss") {
		singular = singular[:len(singular)-1]
	}
	return toPascal(singular)
}

func splitRef(ref string) (table, col string, ok bool) {
	i := strings.LastIndex(ref, ".")
	if i <= 0 || i == len(ref)-1 {
		return "", "", false
	}
	return ref[:i], ref[i+1:], true
}
