# yaml-language-server: $schema=https://raw.githubusercontent.com/dnahilman/goten/main/goten.config.schema.json
plugins:
  - oauth

generate:
  output_dir: ./internal/auth
  package: authmodels
  orm: gorm
