# yaml-language-server: $schema=https://raw.githubusercontent.com/dnahilman/goten/main/goten.config.schema.json
database:
  url: postgres://goten:goten@localhost:5432/goten?sslmode=disable
  driver: postgres

migrations:
  plugins:
    - username
