database:
  url: postgres://goten:goten@localhost:5432/goten?sslmode=disable
  driver: postgres

migrations:
  core_dir: ../../migrations
  plugins:
    - ../../plugins/username/migrations
  table: goten_migrations

generate_dir: ../../migrations
